# default rails 6.1 with postgresql and redis
#
# docker-compose.yml
include:
  - docker-compose.stack.yml

services:

  web:
    build: .
    command: bundle exec rails s -p 3000
    environment:
      - APPSIGNAL_PUSH_API_KEY=${APPSIGNAL_PUSH_API_KEY}
    ports:
      - 3000:3000

  db_migrate:
    build: .
    command: bundle exec rake db:migrate db:seed

  traffic:
    build: .
    command: bundle exec rake traffic:go[web]
    deploy:
      replicas: 4 # decrease to 1 or 2 if you have slow computer
    environment:
      TRAFFIC_GENERATOR_SLEEP_TIME: 1 # increase to 5 or 10 if you have slow computer
      TRAFFIC_GENERATOR_HOST: web
    depends_on:
      - web

  open_tracing_jaeger:
    image: jaegertracing/all-in-one:1.53
    expose:
      - 5775/udp # accept zipkin.thrift over compact thrift protocol
      - 6831/udp # accept jaeger.thrift over compact thrift protocol
      - 6832/udp # accept jaeger.thrift over binary thrift protocol
      - 5778     # serve configs
      - 16686    # serve frontend
      - 14250    # accept jaeger.thrift over binary thrift protocol (deprecated, used by legacy clients only)
      - 14268    # accept jaeger.thrift over compact thrift protocol
      - 14269    # accept jaeger.thrift over binary thrift protocol
      - 9411     # Zipkin HTTP collector
      - 4318     # Jaeger remote sampling HTTP server
      - 4317     # Jaeger remote sampling gRPC server
    ports:
      - 16686:16686
      - 4318:4318



