# default rails 6.1 with postgresql and redis
#
# docker-compose.yml

services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adopter_production
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.9-alpine
    command: redis-server
    ports:
      - 6379:6379

  web:
    build: .
    command: bundle exec rails s -p 3000 -e production
    environment:
      - APPSIGNAL_PUSH_API_KEY=${APPSIGNAL_PUSH_API_KEY}
    ports:
      - 3000:3000
    expose:
      - 3000
  db_migrate:
    build: .
    command: bundle exec rake db:migrate db:seed

  traffic:
    build: .
    command: bundle exec rake traffic:go[web:3000]
    deploy:
      replicas: 4 # decrease to 1 or 2 if you have slow computer
    environment:
      TRAFFIC_GENERATOR_SLEEP_TIME: 1 # increase to 5 or 10 if you have slow computer
      TRAFFIC_GENERATOR_HOST: web:3000
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
