x-adopter: &adopter
  build: .
  volumes:
    - .:/app
  env_file: .env.docker
  environment:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    DATABASE_URL: postgres://postgres:postgres@db:5432/adopter_production
    REDIS_URL: redis://redis:6379/1
  depends_on:
    - db
    - redis

services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adopter_production
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - 5432:5442

  redis:
    image: redis:6.0.9-alpine
    command: redis-server
    ports:
      - 6379:6389

  web:
    <<: *adopter
    command: bundle exec rails s -p 3001 -e production
    environment:
      - APPSIGNAL_PUSH_API_KEY=${APPSIGNAL_PUSH_API_KEY}
    ports:
      - 3001:3001
    expose:
      - 3001
    env_file: .env.docker
  db_migrate:
    <<: *adopter
    command: bundle exec rake db:migrate db:seed
    env_file: .env.docker

  traffic:
    <<: *adopter
    command: bundle exec rake traffic:go[web:3000]
    deploy:
      replicas: 4 # decrease to 1 or 2 if you have slow computer
    environment:
      TRAFFIC_GENERATOR_SLEEP_TIME: 1 # increase to 5 or 10 if you have slow computer
      TRAFFIC_GENERATOR_HOST: web:3001
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
