services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adopter_production
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.9-alpine
    command: redis-server
    ports:
      - 6379:6379

volumes:
    postgres_data:
        driver: local
